interface IData{
    [key:string]:string,
}
const data:IData={
"B":	"Bucureşti",
"AB":	"Alba_Iulia",
"AR":	"Arad",	
"AG":	"Pitesti",	
"BC":	"Bacău",	
"BH":	"Oradea",	
"BN":	"Bistriţa",
"BT":	"Botoşani",	
"BV":	"Braşov",	
"BR":	"Brăila",	
"BZ":	"Buzău",	
"CS":	"Resita",
"CL":	"Călăraşi",	
"CJ":	"Cluj-Napoca",	
"CT":	"Constanţa",	
"CV":	"Sfântu_Gheorghe",	
"DB":	"Târgovişte",	
"DJ":	"Craiova",	
"GL":	"Galaţi",	
"GR":	"Giurgiu",	
"GJ":	"Târgu_Jiu",	
"HR":	"Miercurea_Ciuc",	
"HD":	"Deva",	
"IL":	"Slobozia",	
"IS":	"Iaşi",	
"IF":	"Bucureşti",	
"MM":	"Baia_Mare",	
"MH":	"Drobeta-Turnu_Severin",	
"MS":	"Târgu_Mureş",	
"NT":	"Piatra_Neamţ",	
"OT":	"Slatina",	
"PH":	"Ploieşti",	
"SM":	"Satu Mare", 
"SJ":	"Zalău",	
"SB":	"Sibiu",	
"SV":	"Suceava",	
"TR":	"Alexandria",	
"TM":	"Timişoara",	
"TL":	"Tulcea",	
"VL":	"Râmnicu_Vâlcea",	
"VS":	"Vaslui",	
"VN":	"Focşani"
}
export default {data}